### PR TITLE
Fixes #11

### LINKED ISSUE #11: Warning if Unable to Branch
Currently if you try to branch to an address (that I presume is more than 128 bytes away, although I'm not positive on this exact number), the simulator will just jump to some high memory address and everything will eventually fail.

On a real 6502, I realize that this is expected behavior, however since this is a simulator, I think it would be beneficial to display a warning message in the log indicating that a too distant branch was attempted.

I can (as before) submit a PR after I have a chance to comb through the responsible code if you agree that this would be a good feature to add.

### PR DESCRIPTION
**Pull request by baileyparker**
Fixes #11 (branching beyond allowed range of signed byte)

### CODE REVIEW

**Comment by BigEd** [comment]
I'd like to merge this, or something very like it, but I'd like to test it first. Sorry for the wait.

**Comment by BigEd** [comment]
Looks like this will do the job, what do you think?  If you like it, please tweak your request and I'll merge.

```
      var distance = addr - defaultCodePC - 1;

      if(distance < -128 || distance > 127) {
          wasOutOfRangeBranch = true;
          return false;
      }

      pushByte(distance);
      return true;
```

(It's simpler and we don't need to specialcase backward branches)

**Comment by baileyparker** [comment]
I agree that this is simpler and can make that small tweak. However, won't the `-1` make the bounds checks off by one?

**Comment by BigEd** [comment]
(BTW please could you also trim some of the blank lines in the new code around line 1270?)

Here's my test program, which confirms that the new and old behaviour is the same (apart from the error check) - and also I'm sure the behaviour is right!  (The procedure is to assemble the code then look at the branch operands in the disassembly.)

```
x:
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8

dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8

bcc x
bcs y

dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8

dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8,8
dcb 8,8,8,8, 8,8,8,8, 8,8,8,8, 8,8,8

y:
nop
```

(For a full test, also show that one extra byte in either of the big blocks provokes an error)

**Comment by BigEd** [comment]
(Just to note: I edited my previous comment, possibly after you'd already read it.)

**Pull request merged**
